# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 120bf3173bae727ec55bdc457a87ea039d9b1e73e43d9079d4f1c20e958693b82c107aa70daca4a1e3f8b8fc6f0a89a4e47f4ed963a280ba674f69613b75c10d

test:
  secret_key_base: 626f5b55e53840e08a8b0dca0d01ef5cde703b0494d3b44925888120e87a273092fa414f3844931004b49243074e0cadca91f173cd5661376b8fd7e243598ed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
